# Generated by Django 4.2.20 on 2025-06-14 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('narratives', '0001_initial'),
    ]

    operations = [
    ]
