# Generated by Django 5.2.8 on 2025-11-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_add_owner_thumbnails'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='camera_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='camera_model',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
